#This is a file to config the parameters

# Seed
seed: 1
dir_imgs_ae: "/jmain02/home/J2AD014/mtc03/ccm69-mtc03/multimodal_retina/cvd/fundus_21012/" 
ids_set: "/cmaldonado/multimodal_retina/data/csv/ids_classier_fundus_cvd.csv" 
ids_set_class: "/jmain02/home/J2AD014/mtc03/ccm69-mtc03/multimodal_retina/ids_classifier_cvds.csv"


pretrained_model: "/jmain02/home/J2AD014/mtc03/ccm69-mtc03/multimodal_retina/1af72973695e45b18e34a99681eb1802/epoch=23-step=6383.ckpt"
#36060f713d8f423189eb43c520bc7705/epoch=19-step=9299.ckpt"
#pretrained_model: "/cmaldonado/multimodal_retina/Multimodal-Retina/mlruns/2/7fb3cb89c1774154be729a1289178f5f/checkpoints/epoch=34-step=78224.ckpt" 

input_dim: 3 224 224 
w_bce: 0.5 
w_kld : 0.002


network_architecture:  {
    latent_dim: 2048,
    convolution : {
       parameters : {
          kernel_size: 3 3,
          padding: 1 1,
          stride: 2 2,
          channels: 3 128 256 512 1024 2048, 
          activation_function: relu relu relu relu relu relu relu,
       }
    }
}

classifier: {
   n_classes: 2,
   nhead: 8,
   num_encoder_layers: 1 
}

# Learning Parameters

optimizer: {
  algorithm: "Adam",
  batch_size: 4, 
  parameters: {
    lr: 0.001,
    betas: [0.5, 0.99],
    weight_decay: 0.0000001 

  }
}

mlflow: {
  pretraining: {
    run_name: null,
    experiment_name: "AE"
  },
  classifier_training: {
    run_name: null,
    experiment_name: "VAE + Classifier"
  }
 }
